# Generated by Django 3.1.3 on 2020-11-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('working', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('desc', models.CharField(max_length=35)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('uom', models.CharField(max_length=3)),
                ('lead_time', models.IntegerField(default=0)),
                ('classification', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Code')),
                ('desc', models.CharField(max_length=60)),
                ('case_size', models.IntegerField(blank=True, null=True)),
                ('bulk_code', models.CharField(max_length=7)),
                ('micro', models.BooleanField(blank=True, null=True)),
                ('carton', models.BooleanField(blank=True, null=True)),
                ('bus_category', models.CharField(blank=True, max_length=15, null=True)),
                ('prod_category', models.CharField(max_length=25)),
                ('gr_wt', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('nt_wt', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('plant', models.CharField(choices=[('1024', '1024'), ('1025', '1025')], max_length=4)),
                ('line_bulk', models.CharField(blank=True, max_length=25, null=True)),
                ('des_code', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='StockFG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_released', models.DecimalField(decimal_places=2, max_digits=9)),
                ('qty_quality', models.DecimalField(decimal_places=2, max_digits=9)),
                ('uom', models.CharField(max_length=3)),
                ('material_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_released', models.DecimalField(decimal_places=2, max_digits=9)),
                ('qty_quality', models.DecimalField(decimal_places=2, max_digits=9)),
                ('uom', models.CharField(max_length=3)),
                ('material_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.material')),
            ],
        ),
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.product', to_field='code')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.line', to_field='line')),
            ],
        ),
        migrations.CreateModel(
            name='So',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so', models.CharField(max_length=25)),
                ('so_date', models.DateField()),
                ('so_del_date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('closed', models.BooleanField()),
                ('act_disp_qty', models.IntegerField(default=0, null=True)),
                ('act_disp_date', models.DateField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('INR', 'INR')], max_length=3, null=True)),
                ('customer', models.CharField(max_length=35)),
                ('fgcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.product')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=7)),
                ('doc_date', models.DateField(auto_now=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.line')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('plan_qty', models.IntegerField()),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.line', to_field='line')),
                ('so', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='app1.so')),
            ],
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=9)),
                ('uom', models.CharField(max_length=3)),
                ('active', models.BooleanField()),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.product')),
                ('material_code', models.ManyToManyField(to='app1.Material')),
            ],
        ),
    ]
