# Generated by Django 3.1.3 on 2020-11-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='code',
        ),
        migrations.RemoveField(
            model_name='production',
            name='doc_date',
        ),
        migrations.AddField(
            model_name='production',
            name='so',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.so'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=2, max_digits=7)),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.so')),
            ],
        ),
    ]
