# Generated by Django 3.1.3 on 2020-11-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201129_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
