# Generated by Django 3.1.3 on 2020-11-29 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201129_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
