# Generated by Django 3.1.3 on 2020-11-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20201130_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='classification',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
