# Generated by Django 3.1.3 on 2020-11-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20201130_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=35)),
                ('country', models.CharField(choices=[('Afghanistan', 'Afghanistan'), ('Malaysia', 'Malaysia'), ('Africa', 'Africa'), ('US', 'US'), ('Bangladesh', 'Bangladesh'), ('Canada', 'Canada'), ('Dubai', 'Dubai'), ('Czech Republic', 'Czech Republic'), ('Denmark', 'Denmark'), ('Italy', 'Italy'), ('UK', 'UK'), ('Finland', 'Finland'), ('France', 'France'), ('Fiji', 'Fiji'), ('Myanmar', 'Myanmar'), ('Germany', 'Germany'), ('Netherland', 'Netherland'), ('Qatar', 'Qatar'), ('Russia', 'Russia'), ('Sri Lanka', 'Sri Lanka'), ('Domestic', 'Domestic'), ('Thailand', 'Thailand'), ('Turkey', 'Turkey'), ('Ukraine', 'Ukraine'), ('Japan', 'Japan'), ('Saudi Arabia', 'Saudi Arabia'), ('Jamaica', 'Jamaica'), ('Madagascar', 'Madagascar'), ('Mongolia', 'Mongolia'), ('Iraq', 'Iraq'), ('India', 'India')], max_length=35, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='so',
            name='comitted_disp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='so',
            name='so',
            field=models.CharField(max_length=25, verbose_name='Sales Order'),
        ),
    ]
