# Generated by Django 3.1.3 on 2020-11-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20201130_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cust_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pts',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
    ]
