# Generated by Django 3.1.3 on 2020-11-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20201130_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='so',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.customer'),
        ),
    ]
