# Generated by Django 3.1.3 on 2020-11-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20201130_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
