# Generated by Django 3.1.3 on 2020-11-30 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_product_stripe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='line_bulk',
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.customer'),
        ),
    ]
