# Generated by Django 3.1.3 on 2020-12-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20201201_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bulk_code',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
