# Generated by Django 3.1.3 on 2020-12-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20201201_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='so',
            old_name='comitted_disp_date',
            new_name='committed_disp_date',
        ),
    ]
