# Generated by Django 3.1.3 on 2020-12-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20201201_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('Afghanistan', 'Afghanistan'), ('Malaysia', 'Malaysia'), ('Africa', 'Africa'), ('US', 'US'), ('Bangladesh', 'Bangladesh'), ('Canada', 'Canada'), ('Dubai', 'Dubai'), ('Czech Republic', 'Czech Republic'), ('Denmark', 'Denmark'), ('Italy', 'Italy'), ('UK', 'UK'), ('Finland', 'Finland'), ('France', 'France'), ('Fiji', 'Fiji'), ('Myanmar', 'Myanmar'), ('Germany', 'Germany'), ('Netherland', 'Netherland'), ('Qatar', 'Qatar'), ('Russia', 'Russia'), ('Sri Lanka', 'Sri Lanka'), ('Domestic', 'Domestic'), ('Thailand', 'Thailand'), ('Turkey', 'Turkey'), ('Ukraine', 'Ukraine'), ('Japan', 'Japan'), ('Saudi Arabia', 'Saudi Arabia'), ('Jamaica', 'Jamaica'), ('Madagascar', 'Madagascar'), ('Mongolia', 'Mongolia'), ('Iraq', 'Iraq'), ('India', 'India'), ('Turkmenistan', 'Turkmenistan'), ('West Indies', 'West Indies'), ('Cambodia', 'Cambodia'), ('Yemen', 'Yemen')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='so',
            name='remarks',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
