# Generated by Django 3.1.3 on 2020-12-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20201201_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bus_category',
            field=models.CharField(blank=True, choices=[('Pvt Label', 'Pvt Label'), ('IBD', 'IBD'), ('Domestic', 'Domestic')], max_length=15, null=True),
        ),
    ]
