# Generated by Django 3.1.3 on 2020-12-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20201201_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_category',
            field=models.CharField(choices=[('Pvt Label', 'Pvt Label'), ('IBD', 'IBD'), ('Domestic', 'Domestic')], max_length=25),
        ),
        migrations.AlterField(
            model_name='so',
            name='closed',
            field=models.BooleanField(verbose_name='Closed'),
        ),
    ]
