# Generated by Django 3.1.3 on 2020-12-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20201201_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='so',
            old_name='committed_disp_date',
            new_name='commit_disp_date',
        ),
    ]
