# Generated by Django 3.1.3 on 2020-12-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20201201_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='code',
        ),
        migrations.RemoveField(
            model_name='bomversion',
            name='bom',
        ),
        migrations.AddField(
            model_name='bom',
            name='bomversion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.bomversion'),
        ),
        migrations.AddField(
            model_name='bomversion',
            name='fgcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.product'),
        ),
    ]
