# Generated by Django 3.1.3 on 2020-12-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20201201_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='qty',
            field=models.DecimalField(decimal_places=4, max_digits=11),
        ),
    ]
