# Generated by Django 3.1.3 on 2020-12-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20201202_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='material_code',
            field=models.ManyToManyField(db_table='app1_bom_material_code', to='app1.Material'),
        ),
    ]
