# Generated by Django 3.1.3 on 2020-12-02 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_auto_20201202_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_qty',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 1, 15, 38, 21, 168961)),
        ),
    ]
