# Generated by Django 3.1.3 on 2020-12-04 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_auto_20201202_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 10, 10, 33, 110686)),
        ),
    ]
