# Generated by Django 3.1.3 on 2020-12-04 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_auto_20201204_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 3, 10, 20, 10, 950320)),
        ),
        migrations.AlterField(
            model_name='so',
            name='remarks',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
