# Generated by Django 3.1.3 on 2020-12-07 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_auto_20201204_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatch',
            old_name='qty',
            new_name='dis_qty',
        ),
        migrations.RenameField(
            model_name='production',
            old_name='qty',
            new_name='prod_qty',
        ),
        migrations.RenameField(
            model_name='so',
            old_name='qty',
            new_name='so_qty',
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 6, 14, 28, 18, 221236)),
        ),
    ]
