# Generated by Django 3.1.3 on 2020-12-19 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_auto_20201209_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bulk_code',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 18, 15, 54, 47, 417180)),
        ),
    ]
