# Generated by Django 3.1.3 on 2020-12-22 09:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_auto_20201219_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='bom',
            name='fgcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.product'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='bomversion',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 21, 14, 36, 38, 411257)),
        ),
    ]
