# Generated by Django 3.1.3 on 2020-12-22 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_auto_20201222_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 21, 16, 57, 0, 879705)),
        ),
        migrations.DeleteModel(
            name='BOMVersion',
        ),
    ]
