# Generated by Django 3.1.3 on 2021-01-01 04:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_auto_20201222_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('Afghanistan', 'Afghanistan'), ('Africa', 'Africa'), ('Bangladesh', 'Bangladesh'), ('Canada', 'Canada'), ('Cambodia', 'Cambodia'), ('Czech Republic', 'Czech Republic'), ('Denmark', 'Denmark'), ('Domestic', 'Domestic'), ('Dubai', 'Dubai'), ('Fiji', 'Fiji'), ('Finland', 'Finland'), ('France', 'France'), ('Germany', 'Germany'), ('Italy', 'Italy'), ('India', 'India'), ('Iraq', 'Iraq'), ('Japan', 'Japan'), ('Jamaica', 'Jamaica'), ('Kenya', 'Kenya'), ('Madagascar', 'Madagascar'), ('Malaysia', 'Malaysia'), ('Mongolia', 'Mongolia'), ('Myanmar', 'Myanmar'), ('Netherland', 'Netherland'), ('Qatar', 'Qatar'), ('Russia', 'Russia'), ('Sri Lanka', 'Sri Lanka'), ('Thailand', 'Thailand'), ('Saudi Arabia', 'Saudi Arabia'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan'), ('UK', 'UK'), ('Uganda', 'Uganda'), ('US', 'US'), ('Ukraine', 'Ukraine'), ('West Indies', 'West Indies'), ('Yemen', 'Yemen')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 31, 4, 5, 31, 89709, tzinfo=utc)),
        ),
    ]
