# Generated by Django 3.1.3 on 2021-01-01 04:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_auto_20210101_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 1, 4, 8, 54, 416029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 31, 4, 8, 54, 416029, tzinfo=utc)),
        ),
    ]
