# Generated by Django 3.1.3 on 2021-01-01 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_auto_20210101_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='date',
        ),
        migrations.AddField(
            model_name='production',
            name='prod_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 31, 9, 43, 6, 770762)),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
