# Generated by Django 3.1.3 on 2021-01-01 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_auto_20210101_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='prod_date',
        ),
        migrations.AddField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 31, 9, 44, 2, 358989)),
        ),
    ]
