# Generated by Django 3.1.3 on 2021-01-16 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_auto_20210116_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 15, 14, 38, 2, 793573)),
        ),
    ]
