# Generated by Django 3.1.3 on 2021-01-16 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_auto_20210116_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 15, 14, 38, 56, 698404)),
        ),
    ]
