# Generated by Django 3.1.3 on 2021-01-16 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_auto_20210116_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='lead_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 15, 15, 30, 17, 9982)),
        ),
    ]
