# Generated by Django 3.1.3 on 2021-01-16 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_auto_20210116_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='classification',
            field=models.CharField(blank=True, choices=[('Tube', 'Tube'), ('Carton', 'Carton'), ('CFB', 'CFB'), ('Sticker', 'Sticker'), ('RM', 'RM'), ('Powder', 'Powder')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 15, 15, 39, 5, 803451)),
        ),
    ]
