# Generated by Django 3.1.3 on 2021-01-16 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0055_auto_20210116_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 15, 15, 44, 56, 471405)),
        ),
    ]
