# Generated by Django 3.1.3 on 2021-01-16 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0056_auto_20210116_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='uom',
            field=models.CharField(choices=[('NO', 'NO'), ('TS', 'TS'), ('KG', 'KG'), ('G', 'G')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 15, 16, 56, 7, 974884)),
        ),
    ]
