# Generated by Django 3.1.3 on 2021-02-14 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0057_auto_20210116_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='bus_category',
            field=models.CharField(blank=True, choices=[('Pvt Label', 'Pvt Label'), ('IBD', 'IBD'), ('Domestic', 'Domestic')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='case_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='cbm',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='cust_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.customer'),
        ),
        migrations.AddField(
            model_name='material',
            name='des_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='gr_wt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='micro',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='nt_wt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='plant',
            field=models.CharField(blank=True, choices=[('1024', '1024'), ('1025', '1025')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='prod_category',
            field=models.CharField(blank=True, choices=[('Toothpaste', 'Toothpaste'), ('Toothpaste Pouch', 'Toothpaste Pouch'), ('Mouthwash', 'Mouthwash'), ('Toothpowder', 'Toothpowder'), ('Odonil', 'Odonil'), ('Bleach', 'Bleach'), ('Bleach Intermediate', 'Bleach Intermediate'), ('Odomos Lotion', 'Odomos Lotion'), ('HRC', 'HRC'), ('Petroleum Jelly', 'Petroleum Jelly'), ('Creamy PJ', 'Creamy PJ'), ('Handwash', 'Handwash'), ('Odomos', 'Odomos'), ('Denture Adhesive', 'Denture Adhesive'), ('Shaving Cream', 'Shaving Cream')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='pts',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='remarks',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('Afghanistan', 'Afghanistan'), ('Africa', 'Africa'), ('Bangladesh', 'Bangladesh'), ('Canada', 'Canada'), ('Cambodia', 'Cambodia'), ('Czech Republic', 'Czech Republic'), ('Denmark', 'Denmark'), ('Domestic', 'Domestic'), ('Dubai', 'Dubai'), ('Fiji', 'Fiji'), ('Finland', 'Finland'), ('France', 'France'), ('Germany', 'Germany'), ('Italy', 'Italy'), ('India', 'India'), ('Iraq', 'Iraq'), ('Japan', 'Japan'), ('Jamaica', 'Jamaica'), ('Kenya', 'Kenya'), ('Madagascar', 'Madagascar'), ('Malaysia', 'Malaysia'), ('Mongolia', 'Mongolia'), ('Myanmar', 'Myanmar'), ('Netherland', 'Netherland'), ('Qatar', 'Qatar'), ('Russia', 'Russia'), ('Sri Lanka', 'Sri Lanka'), ('Thailand', 'Thailand'), ('Saudi Arabia', 'Saudi Arabia'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan'), ('UAE', 'UAE'), ('UK', 'UK'), ('Uganda', 'Uganda'), ('US', 'US'), ('Ukraine', 'Ukraine'), ('West Indies', 'West Indies'), ('Yemen', 'Yemen')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='classification',
            field=models.CharField(blank=True, choices=[('FG', 'FG'), ('Bulk', 'Bulk'), ('Tube', 'Tube'), ('Carton', 'Carton'), ('CFB', 'CFB'), ('Sticker', 'Sticker'), ('RM', 'RM'), ('Powder', 'Powder')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 13, 15, 49, 6, 455751)),
        ),
    ]
