# Generated by Django 3.1.3 on 2021-02-14 15:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0061_auto_20210214_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 13, 20, 43, 42, 765846)),
        ),
        migrations.AlterField(
            model_name='so',
            name='fgcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.product'),
        ),
    ]
