# Generated by Django 3.1.3 on 2021-02-14 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0062_auto_20210214_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 13, 20, 45, 45, 176152)),
        ),
    ]
