# Generated by Django 3.1.3 on 2021-02-14 15:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0064_auto_20210214_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='so',
            name='fgcode',
        ),
        migrations.AddField(
            model_name='so',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.material'),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 13, 21, 29, 15, 527550)),
        ),
    ]
