# Generated by Django 3.1.3 on 2021-02-14 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0066_auto_20210214_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 13, 21, 49, 12, 675028)),
        ),
        migrations.DeleteModel(
            name='StockFG',
        ),
    ]
