# Generated by Django 3.1.3 on 2021-02-14 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0069_auto_20210214_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 13, 22, 17, 29, 533210)),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
