# Generated by Django 3.1.3 on 2021-02-15 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0071_auto_20210215_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='line',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 14, 11, 21, 25, 710701)),
        ),
    ]
