# Generated by Django 3.1.3 on 2021-02-15 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_auto_20210215_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='speed',
            name='manpower',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 14, 16, 14, 34, 247303)),
        ),
        migrations.CreateModel(
            name='WCGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wcgrp', models.CharField(max_length=5)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.line', to_field='line')),
            ],
        ),
    ]
