# Generated by Django 3.1.3 on 2021-02-27 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0076_auto_20210219_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='active',
            field=models.BooleanField(verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='bomversion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bom',
            name='uom',
            field=models.CharField(choices=[('NO', 'NO'), ('TS', 'TS'), ('KG', 'KG'), ('G', 'G')], max_length=3),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 26, 16, 26, 14, 871184)),
        ),
    ]
