# Generated by Django 3.1.3 on 2021-02-27 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0077_auto_20210227_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.material'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='uom',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('TS', 'TS'), ('KG', 'KG'), ('G', 'G')], max_length=3),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 26, 16, 38, 11, 820631)),
        ),
    ]
