# Generated by Django 3.1.3 on 2021-03-06 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0080_auto_20210306_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 5, 10, 51, 17, 214946)),
        ),
        migrations.AlterField(
            model_name='so',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
