# Generated by Django 3.1.3 on 2021-03-08 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0082_auto_20210308_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 7, 10, 42, 37, 609039)),
        ),
    ]
