# Generated by Django 3.1.3 on 2021-03-08 05:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0084_auto_20210308_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.material', to_field='code'),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 7, 10, 59, 41, 746458)),
        ),
    ]
