# Generated by Django 3.1.3 on 2021-03-08 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0086_auto_20210308_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='dem_month',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 7, 14, 55, 35, 281680)),
        ),
    ]
