# Generated by Django 3.1.3 on 2021-03-08 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0088_auto_20210308_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='qty',
            new_name='fore_qty',
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 7, 15, 2, 9, 473689)),
        ),
    ]
