# Generated by Django 3.1.3 on 2021-03-08 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0089_auto_20210308_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='dem_month',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 7, 15, 10, 36, 656414)),
        ),
    ]
