# Generated by Django 3.1.3 on 2021-03-08 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0092_auto_20210308_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='dem_month',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 7, 15, 18, 52, 563774)),
        ),
    ]
