# Generated by Django 3.1.3 on 2021-04-05 04:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0093_auto_20210308_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 4, 9, 40, 41, 491797)),
        ),
        migrations.CreateModel(
            name='Fmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.BinaryField()),
                ('alg', models.CharField(choices=[('Random Forrest', 'Random Forrest'), ('SVM', 'SVM'), ('Linear Regression', 'Linear Regression'), ('ARIMAX', 'ARIMAX')], max_length=21)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.material')),
            ],
        ),
    ]
