# Generated by Django 3.1.3 on 2021-04-06 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0095_auto_20210406_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='dem_month1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 8, 46, 6, 65429)),
        ),
    ]
