# Generated by Django 3.1.3 on 2021-04-06 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0096_auto_20210406_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 8, 48, 3, 700574)),
        ),
    ]
