# Generated by Django 3.1.3 on 2021-04-06 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0099_auto_20210406_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmodel',
            name='mase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 21, 8, 11, 312397)),
        ),
    ]
