# Generated by Django 3.1.3 on 2021-04-12 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0100_auto_20210406_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='wcgroup',
            name='set_time',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 11, 8, 46, 29, 727919)),
        ),
    ]
