# Generated by Django 3.1.3 on 2021-04-12 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0102_auto_20210412_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 11, 14, 23, 52, 207438)),
        ),
    ]
