# Generated by Django 3.1.3 on 2021-04-12 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0104_auto_20210412_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='month1',
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 11, 14, 34, 40, 346306)),
        ),
    ]
