# Generated by Django 3.1.3 on 2021-04-18 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0105_auto_20210412_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='overr_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 17, 15, 38, 40, 680959)),
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=datetime.datetime.now)),
                ('mps_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.material')),
            ],
        ),
    ]
