# Generated by Django 3.1.3 on 2021-04-20 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0107_auto_20210420_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 16, 13, 53, 130033)),
        ),
    ]
