# Generated by Django 3.1.3 on 2021-04-29 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0108_auto_20210420_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='lot_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='atp_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='pab_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 28, 7, 10, 19, 922068)),
        ),
    ]
