# Generated by Django 3.1.3 on 2021-05-22 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0109_auto_20210429_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='so',
            name='prod_comp',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 21, 15, 52, 40, 584589)),
        ),
    ]
