# Generated by Django 3.1.3 on 2021-05-31 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0110_auto_20210522_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='so',
            name='prod_comp',
        ),
        migrations.AlterField(
            model_name='line',
            name='prod_category',
            field=models.CharField(choices=[('Toothpaste', 'Toothpaste'), ('Toothpaste Pouch', 'Toothpaste Pouch'), ('Mouthwash', 'Mouthwash'), ('Toothpowder', 'Toothpowder'), ('Odonil', 'Odonil'), ('Bleach', 'Bleach'), ('Bleach Intermediate', 'Bleach Intermediate'), ('Odomos Lotion', 'Odomos Lotion'), ('HRC', 'HRC'), ('Petroleum Jelly', 'Petroleum Jelly'), ('Creamy PJ', 'Creamy PJ'), ('Handwash', 'Handwash'), ('Odomos', 'Odomos'), ('Denture Adhesive', 'Denture Adhesive'), ('Shaving Cream', 'Shaving Cream'), ('Loose', 'Loose')], max_length=25),
        ),
        migrations.AlterField(
            model_name='material',
            name='prod_category',
            field=models.CharField(blank=True, choices=[('Toothpaste', 'Toothpaste'), ('Toothpaste Pouch', 'Toothpaste Pouch'), ('Mouthwash', 'Mouthwash'), ('Toothpowder', 'Toothpowder'), ('Odonil', 'Odonil'), ('Bleach', 'Bleach'), ('Bleach Intermediate', 'Bleach Intermediate'), ('Odomos Lotion', 'Odomos Lotion'), ('HRC', 'HRC'), ('Petroleum Jelly', 'Petroleum Jelly'), ('Creamy PJ', 'Creamy PJ'), ('Handwash', 'Handwash'), ('Odomos', 'Odomos'), ('Denture Adhesive', 'Denture Adhesive'), ('Shaving Cream', 'Shaving Cream'), ('Loose', 'Loose')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 30, 11, 27, 51, 996483)),
        ),
    ]
